namespace PaketLoadScripts

#r "C:\\Users\\benji\\.nuget\\packages\\argu\\6.1.1\\lib\\netstandard2.0\\Argu.dll" 
#r "C:\\Users\\benji\\.nuget\\packages\\system.security.cryptography.protecteddata\\6.0.0\\lib\\netstandard2.0\\System.Security.Cryptography.ProtectedData.dll" 
#r "C:\\Users\\benji\\.nuget\\packages\\fparsec\\1.1.1\\lib\\netstandard2.0\\FParsecCS.dll" 
#r "C:\\Users\\benji\\.nuget\\packages\\system.drawing.common\\6.0.0\\lib\\netcoreapp3.1\\System.Drawing.Common.dll" 
#r "C:\\Users\\benji\\.nuget\\packages\\mathnet.numerics\\5.0.0\\lib\\net5.0\\MathNet.Numerics.dll" 
#r "C:\\Users\\benji\\.nuget\\packages\\microsoft.win32.systemevents\\6.0.1\\lib\\netcoreapp3.1\\Microsoft.Win32.SystemEvents.dll" 
#r "C:\\Users\\benji\\.nuget\\packages\\system.runtime.compilerservices.unsafe\\6.0.0\\lib\\netcoreapp3.1\\System.Runtime.CompilerServices.Unsafe.dll" 
#r "C:\\Users\\benji\\.nuget\\packages\\system.security.principal.windows\\5.0.0\\lib\\netstandard2.0\\System.Security.Principal.Windows.dll" 
#r "C:\\Users\\benji\\.nuget\\packages\\system.windows.extensions\\6.0.0\\lib\\netcoreapp3.1\\System.Windows.Extensions.dll" 
#r "C:\\Users\\benji\\.nuget\\packages\\fparsec\\1.1.1\\lib\\netstandard2.0\\FParsec.dll" 
#r "C:\\Users\\benji\\.nuget\\packages\\mathnet.numerics.fsharp\\5.0.0\\lib\\net5.0\\MathNet.Numerics.FSharp.dll" 
#r "C:\\Users\\benji\\.nuget\\packages\\system.security.accesscontrol\\6.0.0\\lib\\netstandard2.0\\System.Security.AccessControl.dll" 
#r "C:\\Users\\benji\\.nuget\\packages\\system.security.permissions\\6.0.0\\lib\\net5.0\\System.Security.Permissions.dll" 
#r "C:\\Users\\benji\\.nuget\\packages\\system.configuration.configurationmanager\\6.0.0\\lib\\netstandard2.0\\System.Configuration.ConfigurationManager.dll" 